// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    copy: typeof import("./components/TheEditor copy.vue")["default"];
    FormErrors: typeof import("./components/FormErrors.vue")["default"];
    HelloWorld: typeof import("./components/HelloWorld.vue")["default"];
    MainButton: typeof import("./components/MainButton.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TheEditor: typeof import("./components/TheEditor.vue")["default"];
    TheForm: typeof import("./components/TheForm.vue")["default"];
    TheHeader: typeof import("./components/TheHeader.vue")["default"];
  }
}
